// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ZigVS.Command
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidZigVSPackageString = "3fd9286d-949f-4d6e-a11a-1493feb6f915";
        public static Guid guidZigVSPackage = new Guid(guidZigVSPackageString);

        public const string guidZigVSPackageCmdSetString = "875694cf-4e47-4e92-a15e-c6f296281c12";
        public static Guid guidZigVSPackageCmdSet = new Guid(guidZigVSPackageCmdSetString);

        public const string guidWorkspaceExplorerBuildActionCmdSetString = "16537f6e-cb14-44da-b087-d1387ce3bf57";
        public static Guid guidWorkspaceExplorerBuildActionCmdSet = new Guid(guidWorkspaceExplorerBuildActionCmdSetString);

        public const string guidWorkspaceExplorerToolWindowPackageCmdSetString = "cfb400f1-5c60-4f3c-856e-180d28def0b7";
        public static Guid guidWorkspaceExplorerToolWindowPackageCmdSet = new Guid(guidWorkspaceExplorerToolWindowPackageCmdSetString);

        public const string StandardCommandSet2kString = "1496a755-94de-11d0-8c3f-00c04fc2aae2";
        public static Guid StandardCommandSet2k = new Guid(StandardCommandSet2kString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TopLevelMenuId = 0x0100;
        public const int SubMenuGroupId = 0x0200;
        public const int ToolChainInstallerId = 0x1000;
        public const int PachageInstallerId = 0x2000;
        public const int HelpId = 0x3000;
        public const int QAndAId = 0x6000;
        public const int RatingAndReviewId = 0x7000;
        public const int PachageCreaterId = 0x4000;
        public const int FormattingCommandId = 0x0300;
        public const int ToggleInlyHintsId = 0x5000;
        public const int ToolbarId = 0x0350;
        public const int ToolbarGroupid = 0x0400;
        public const int DebuggerDropDownComboId = 0x0500;
        public const int DebuggerDropDownComboListCommandId = 0x0600;
        public const int BuildActionContext = 0x1000;
        public const int RebuildActionContext = 0x1010;
        public const int CleanActionContext = 0x1020;
        public const int idmWSE_ContextMenu = 0x0002;
        public const int idgWSE_ContextMenu_ItemActions = 0x0010;
        public const int idgWSE_ContextMenu_CollectionActions = 0x0011;
        public const int idgWSE_ContextMenu_Adding = 0x0012;
        public const int idgWSE_ContextMenu_SccCommands = 0x0013;
        public const int idgWSE_ContextMenu_BuildDebugActions = 0x0014;
        public const int idgWSE_ContextMenu_ShellActions = 0x0015;
        public const int idgWSE_ContextMenu_ScopeActions = 0x0016;
        public const int idgWSE_ContextMenu_FileContextActions = 0x0017;
    }
}